---
name: Release

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    uses: ./.github/workflows/build.dispatch.yaml
    permissions:
      contents: write
      id-token: write
      attestations: write

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: ${{ needs.build.outputs.artifact-name }}

      - name: Create release
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2.4.0
        with:
          body_path: ${{ needs.build.outputs.notes-file-name }}
          files: |
            ${{ needs.build.outputs.tarball-file-name }}
            ${{ needs.build.outputs.attestation-file-name }}
